name: Local CI/CD

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # - name: Install
      #   run: npm install

      # - name: Test
      #   run: npm test

      - name: Write env
        run: |
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          
      - name: Setup SSH agent and test connection
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: SSH connectivity check
        run: |
          ssh -o StrictHostKeyChecking=no -o ConnectTimeout=10 -vvv ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} echo connected

      - name: SSH Deploy to your Ubuntu
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 90s
          script: |
            cd ~/node-crud-app
            git pull origin master
            docker-compose down
            docker-compose build
            docker-compose up -d
